# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

class TopologyViz:
    def discover(self) -> bool: ...
    def load_json(self, json_str: str) -> bool: ...
    def load_json_file(self, path: str) -> bool: ...
    def enrich(self) -> bool: ...
    @property
    def is_ready(self) -> bool: ...
    def to_json(self, indent: int = 2) -> str: ...
    def to_dict(self) -> dict: ...
